#include "VulkanDescriptor.hpp"

VkDescriptorSetLayoutCreateInfo vlibDescriptorSetLayoutCreateInfo = {
	VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
	nullptr,
	0,
	0,
	nullptr
};

VkDescriptorSetAllocateInfo vlibAllocateInfo = {
	VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
	nullptr,
	VK_NULL_HANDLE,
	1,
	VK_NULL_HANDLE
};

VkDescriptorPoolCreateInfo vlibDescriptorPoolCreateInfo = {
	VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
	nullptr,
	VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT,
	400, //TODO Make this autogenerated
	0,
	nullptr
};

VkDescriptorPoolSize vlibDescriptorPoolSize = {
	VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
	0
};

VkWriteDescriptorSet vlibDescriptorWrites = {
		VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
		nullptr,
		VK_NULL_HANDLE,
		0,
		0,
		1,
		VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
		nullptr,
		nullptr,
		nullptr
};

//Pipeline Layout
VkPipelineLayoutCreateInfo vlibLayoutInfo = {
	VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
	nullptr,
	0,
	1,
	nullptr,
	0,
	nullptr
};
