#pragma once

#include "../Stdbase.hpp"

extern VkDescriptorSetLayoutCreateInfo vlibDescriptorSetLayoutCreateInfo;
extern VkDescriptorSetAllocateInfo vlibAllocateInfo;
extern VkDescriptorPoolCreateInfo vlibDescriptorPoolCreateInfo;
extern VkDescriptorPoolSize vlibDescriptorPoolSize;
extern VkWriteDescriptorSet vlibDescriptorWrites;
extern VkPipelineLayoutCreateInfo vlibLayoutInfo;
