#pragma once

#include "../Stdbase.hpp"

extern VkDescriptorSetLayoutCreateInfo vlib_descriptor_set_layout_create_info;
extern VkDescriptorSetAllocateInfo vlib_allocate_info;
extern VkDescriptorPoolCreateInfo vlib_descriptor_pool_create_info;
extern VkDescriptorPoolSize vlib_descriptor_pool_size;
extern VkWriteDescriptorSet vlib_descriptor_writes;
extern VkPipelineLayoutCreateInfo vlib_layout_info;
