#include "VulkanImage.hpp"

VkImageCreateInfo vlib_image_create_info = {
	VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
	nullptr,
	0,
	VK_IMAGE_TYPE_2D,
	VK_FORMAT_UNDEFINED,
	{
		0,
		0,
		1
	},
	1,
	1,
	VK_SAMPLE_COUNT_1_BIT,
	VK_IMAGE_TILING_OPTIMAL,
	VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT,
	VK_SHARING_MODE_EXCLUSIVE,
	0,
	nullptr,
	VK_IMAGE_LAYOUT_UNDEFINED
};

VkImageViewCreateInfo vlib_image_view_create_info = {
	VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
	nullptr,
	0,
	nullptr,
	VK_IMAGE_VIEW_TYPE_2D,
	VK_FORMAT_UNDEFINED,
	{
		VK_COMPONENT_SWIZZLE_IDENTITY,
		VK_COMPONENT_SWIZZLE_IDENTITY,
		VK_COMPONENT_SWIZZLE_IDENTITY,
		VK_COMPONENT_SWIZZLE_IDENTITY
	},
	{
		VK_IMAGE_ASPECT_COLOR_BIT,
		0,
		1,
		0,
		1
	}
};

VkMemoryAllocateInfo vlib_buffer_memory_allocate_info = {
	VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
	nullptr,
	0,
	0
};