#pragma once

#define USAGE(enum_usage) // USAGE OF <type>
#define USAGE_DOCS USAGE("DOCUMANTATION")
#define USAGE_DEBUG USAGE("DEBUG")

#define TARGET(enum_target) // TARGET OF ANNOTATION
#define TARGET_METHODE TARGET("METHODE")
#define TARGET_CODE TARGET("CODE")

USAGE_DOCS
TARGET_CODE
TARGET_METHODE
#define DEPRECATED //DEPRECATED CODE

USAGE_DOCS
TARGET_CODE
#define END_DEPRECATED //END OF DEPRECATED CODE

USAGE_DOCS
TARGET_METHODE
TARGET_CODE
#define UNFINISHED //UNFINISHED CODE

USAGE_DOCS
TARGET_CODE
#define END_UNFINISHED //UNFINISHED CODE

USAGE_DOCS
TARGET_METHODE
#define SINCE(major, minor, version) //SINCE