#include "FontTables.hpp"

void acntTable::extractDataToStruct(std::ifstream str) {}
void ankrTable::extractDataToStruct(std::ifstream str) {}
void avarTable::extractDataToStruct(std::ifstream str) {}
void bdatTable::extractDataToStruct(std::ifstream str) {}
void bhedTable::extractDataToStruct(std::ifstream str) {}
void blocTable::extractDataToStruct(std::ifstream str) {}
void bslnTable::extractDataToStruct(std::ifstream str) {}
void cmapTable::extractDataToStruct(std::ifstream str) {}
void cvarTable::extractDataToStruct(std::ifstream str) {}
void cvtTable::extractDataToStruct(std::ifstream str) {}
void EBSCTable::extractDataToStruct(std::ifstream str) {}
void fdscTable::extractDataToStruct(std::ifstream str) {}
void featTable::extractDataToStruct(std::ifstream str) {}
void fmtxTable::extractDataToStruct(std::ifstream str) {}
void fondTable::extractDataToStruct(std::ifstream str) {}
void fpgmTable::extractDataToStruct(std::ifstream str) {}
void fvarTable::extractDataToStruct(std::ifstream str) {}
void gaspTable::extractDataToStruct(std::ifstream str) {}
void glyfTable::extractDataToStruct(std::ifstream str) {}
void gvarTable::extractDataToStruct(std::ifstream str) {}
void hdmxTable::extractDataToStruct(std::ifstream str) {}
void headTable::extractDataToStruct(std::ifstream str) {}
void hheaTable::extractDataToStruct(std::ifstream str) {}
void hmtxTable::extractDataToStruct(std::ifstream str) {}
void justTable::extractDataToStruct(std::ifstream str) {}
void kernTable::extractDataToStruct(std::ifstream str) {}
void kerxTable::extractDataToStruct(std::ifstream str) {}
void lcarTable::extractDataToStruct(std::ifstream str) {}
void locaTable::extractDataToStruct(std::ifstream str) {}
void ltagTable::extractDataToStruct(std::ifstream str) {}
void maxpTable::extractDataToStruct(std::ifstream str) {}
void metaTable::extractDataToStruct(std::ifstream str) {}
void mortTable::extractDataToStruct(std::ifstream str) {}
void morxTable::extractDataToStruct(std::ifstream str) {}
void nameTable::extractDataToStruct(std::ifstream str) {}
void opbdTable::extractDataToStruct(std::ifstream str) {}
void OSSLASH2Table::extractDataToStruct(std::ifstream str) {}
void prepTable::extractDataToStruct(std::ifstream str) {}
void propTable::extractDataToStruct(std::ifstream str) {}
void sbixTable::extractDataToStruct(std::ifstream str) {}
void trakTable::extractDataToStruct(std::ifstream str) {}
void vheaTable::extractDataToStruct(std::ifstream str) {}
void vmtxTable::extractDataToStruct(std::ifstream str) {}
void xrefTable::extractDataToStruct(std::ifstream str) {}
void ZapfTable::extractDataToStruct(std::ifstream str) {}
