#pragma once

#include "vulkan\vulkan.h"

namespace Options {
	VkPresentModeKHR PRESENT_MODE_USED = VK_PRESENT_MODE_MAILBOX_KHR;
	int PREFERRED_MINIMAL_FRAME_COUNT = 3;
	VkSharingMode PREFERRED_SHARING_MODE = VK_SHARING_MODE_EXCLUSIVE;
	VkImageUsageFlags IMAGE_USAGE = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
}